export const Project: Project_data[] = [
  {
    title: "Modern Next.js 13 Portfolio",
    video_key: "HvkrAjHJ-38",
    say_xi: "Have a great day!",
    say_xi_blog:
      "My portfolio project built with Next.js 13 — featuring a clean UI, basic animations, and authentication.",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Framer Motion",
    ],
    about_this_app:
      "Contain StarMode , Drop Down NavBar , Authentication Google , Facebook , Github , Instgram , Custom Star Colour Basic Animation With Fraimer Motion , Conatin Embed Youtube Video ",
    design_blog: " Ui/Ux Desing & All Code Written by Me  ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use NPM",
    package: [
      "@heroicons/react",
      "@react-three/drei",
      "@react-three/fiber",
      "@reduxjs/toolkit",
      "framer-motion",
      "maath",
      "react-redux",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/v3LJMcWbcDQ",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/HyatMyat_Profiol/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/projects-images/nextjs-profiol.png",
    project_blog:
      "Contain StarMode , Authentication Google , Facebook , Github , Instgram , Custom Star Colour Basic Animation With Fraimer Motion",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Shoe E-Commerce & Admin Dashboard",
    video_key: "v3LJMcWbcDQ",
    say_xi: "Hello, my friends!",
    say_xi_blog:
      "A full-stack responsive shoe e-commerce and admin dashboard. I gained extensive experience with complex UI, authentication, and CRUD operations.",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Postger sql",
      "Firebase",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack Responsive Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Promote Product CRUD Admin Can look How Much User & Chart Pie , Chart line and Auth Google , Nike Auth",
    design_blog:
      "I Found Very Basic Ui Desing From Youtube , Then i get ideal To Make This All Desing By me 💚💚 ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use NPM",
    package: [
      "@mui/material",
      "@nivo/core",
      "@nivo/line",
      "@nivo/pie",
      "@reduxjs/toolkit",
      "@splidejs/react-splide",
      "@stripe/stripe-js",
      "@uiball/loaders",
      "next-auth",
      "next-themes",
      "firebase",
      "javascript-time-ago",
      "jwt-decode",
      "react-circular-progressbar",
      "react-datepicker",
      "react-easy-crop",
      "react-icons",
      "react-hot-toast",
      "react-redux",
      "react-tilt",
      "uuid",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/v3LJMcWbcDQ",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Shoes/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Backend/archive/refs/heads/main.zip",
    project_image: "/projects-images/shoe-ecommerce.png",
    project_blog:
      "A Real Time Full Stack Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Admin Dashboard Web App",
    video_key: "yF1oJ7wzvWY",
    say_xi: "Responsive food ordering project",
    say_xi_blog:
      "Food ordering project with a GraphQL server, user authentication, CRUD operations, and social login integration.",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Responsive Desing",
    design_blog:
      "desing and all of ui create by my own ideal , conatin Backend ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Yarn",
    package: [
      "@apollo/client",
      "@emotion/react",
      "@emotion/styled",
      "@mui/material",
      "@mui/x-data-grid",
      "@nivo/bar",
      "@nivo/core",
      "@nivo/line",
      "@nivo/pie",
      "@reduxjs/toolkit",
      "@stripe/stripe-js",
      "@uiball/loaders",
      "encoding",
      "firebase",
      "graphql",
      "jwt-decode",
      "react-datepicker",
      "next-themes",
      "next-auth",
      "swiper",
      "uuid",
      "redux",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/yF1oJ7wzvWY",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/AdminDashboard/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
    project_image: "/projects-images/admin-dashboard-food.png",
    project_blog:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Deliveroo Mobile App",
    video_key: "AxQ_Eli8gtk",
    say_xi: "My first mobile app",
    say_xi_blog:
      "A React Native project built with Expo CLI, featuring Google authentication, REST API integration, and Google Maps functionality.",
    technology_feature: [
      "Tailwind",
      "React Native",
      "Redux",
      "Type Script",
      "Expo",
      "Node js",
      "Express js",
      "Postger sql",
    ],

    about_this_app:
      "It My First ReactNative App So The have a lot of Bug!, Feature Conatin Google Auth UserCanOrder Remove Order And Containe ReactNativeMap Justlike Deliveroo",
    design_blog: "Desing From PapaReact YouTube Channel",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case we use Yarn and since this project was developed using expo we can also use the expo-cli to install the dependencies.",
    package: [
      "expo",
      "react-native-gesture-handler",
      "react-native-heroicons",
      "react-native-maps",
      "react-native-progress",
      "react-native-safe-area-context",
      "react-native-screens",
      "react-native-svg",
      "react-redux",
      "typescript",
      "nativewind",
      "expo-splash-screen",
      "@react-navigation/native",
      "@react-native-masked-view/masked-view",
      "@react-native-async-storage/async-storage",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/AxQ_Eli8gtk",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Deliveroo_Mobile.apk/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Deliveroo/archive/refs/heads/main.zip",
    project_image: "",
    project_blog:
      "It My First ReactNative App So The have a lot of Bug!, Feature Conatin Google Auth UserCanOrder Remove Order And Containe ReactNativeMap Justlike Deliveroo",
    Type: "React Native",
    project_Img_Mobile: [
      "/projects-images/deliveroo-1.jpg",
      "/projects-images/deliveroo-2.jpg",
      "/projects-images/deliveroo-3.jpg",
      "/projects-images/deliveroo-4.jpg",
      "/projects-images/deliveroo-5.jpg",
    ],
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Full-Stack Food Ordering Website",
    video_key: "yF1oJ7wzvWY",
    say_xi: "Responsive food ordering project",
    say_xi_blog:
      "Food ordering project with a GraphQL server, user authentication, CRUD operations, and social login integration.",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Responsive Desing",
    design_blog:
      "desing and all of ui create by my own ideal , conatin Backend ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Yarn",
    package: [
      "@apollo/client",
      "@emotion/react",
      "@emotion/styled",
      "@mui/material",
      "@mui/x-data-grid",
      "@nivo/bar",
      "@nivo/core",
      "@nivo/line",
      "@nivo/pie",
      "@reduxjs/toolkit",
      "@stripe/stripe-js",
      "@uiball/loaders",
      "encoding",
      "firebase",
      "graphql",
      "jwt-decode",
      "react-datepicker",
      "next-themes",
      "next-auth",
      "swiper",
      "uuid",
      "redux",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/yF1oJ7wzvWY",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/AdminDashboard/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
    project_image: "/projects-images/food-order.png",
    project_blog:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "3 years ago",
  },

  {
    title: "Full-Stack AI ChatGPT Clone",
    video_key: "R90bxY4UwPg",
    say_xi: "Hello, my friends!",
    say_xi_blog:
      "My first AI project — data comes from the OpenAI API. Ask questions just like in the real ChatGPT.",
    technology_feature: [
      "html",
      "css",
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Firebase",
    ],

    about_this_app:
      "This Appp Contain Chate Create , Read , Update , Delete and Google Authentication , Microsoft Authentication , JWT Authentication functionality ",
    design_blog: "Desing From Realworld ChatGPT",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Npm ",
    package: [
      "@reduxjs/toolkit",
      "@uiball/loaders",
      "firebase",
      "firebase-admin",
      "nextjs-progressbar",
      "openai",
      "react-firebase-hooks",
      "react-icons",
      "react-redux",
      "react-simple-typewriter",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/R90bxY4UwPg",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Chat_GPT4/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/projects-images/chatgpt-clone.png",
    project_blog:
      "A Real Time You Can Ask any thing & you can create new chat delete chat & Clear conversations Feature and google , microsoft Auth",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Nike Admin Dashboard Web App",
    video_key: "v3LJMcWbcDQ",
    say_xi: "Hello, my friends!",
    say_xi_blog:
      "A full-stack responsive shoe e-commerce and admin dashboard. I gained extensive experience with complex UI, authentication, and CRUD operations.",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Postger sql",
      "Firebase",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack Responsive Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Promote Product CRUD Admin Can look How Much User & Chart Pie , Chart line and Auth Google , Nike Auth",
    design_blog:
      "I Found Very Basic Ui Desing From Youtube , Then i get ideal To Make This All Desing By me 💚💚 ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use NPM",
    package: [
      "@mui/material",
      "@nivo/core",
      "@nivo/line",
      "@nivo/pie",
      "@reduxjs/toolkit",
      "@splidejs/react-splide",
      "@stripe/stripe-js",
      "@uiball/loaders",
      "next-auth",
      "next-themes",
      "firebase",
      "javascript-time-ago",
      "jwt-decode",
      "react-circular-progressbar",
      "react-datepicker",
      "react-easy-crop",
      "react-icons",
      "react-hot-toast",
      "react-redux",
      "react-tilt",
      "uuid",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/v3LJMcWbcDQ",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Shoes/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Backend/archive/refs/heads/main.zip",
    project_image: "/projects-images/nike-dashboard.png",
    project_blog:
      "A Real Time Full Stack Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Modern Three.js Portfolio",
    video_key: "6wzf2ho-kzI",
    say_xi: "Hello, my friend!",
    say_xi_blog:
      "A responsive 3.js portfolio website with star mode, background music, light/dark mode, embedded YouTube videos, and a mobile-responsive layout built with Vite.",
    technology_feature: [
      "html",
      "css",
      "Javascript",
      "Tailwind",
      "React",
      "Redux",
      "Threes js",
      "Framer Motion",
    ],
    about_this_app:
      "This Responsive  Website is Make for showcase Project Profile ",
    design_blog:
      "very basic desing from My Friends , and I ReModified It All Code & Desing by Me ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I use npm beacuse We use older npm package .",
    package: [
      " maath",
      " @react-three/fiber",
      " @emailjs/browser",
      " framer-motion",
      " @react-three/fiber ",
      " @reduxjs/toolkit ",
      " react-router-dom",
      " react-tilt",
      " react-simple-typewriter",
      " react-icons",
      " react-spinkit",
      " react-vertical-timeline-component",
      " three",
    ],
    conclusion_blog:
      "As I said at the beginning, this is a great project for begginers and even for those who are not new to React . I bealive this is a grat project to have in a resume or portfolio. I am very happy with the app and I hope you will enjoy it as well.",
    youtube_link: "https://youtu.be/6wzf2ho-kzI",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Profiol_2/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/projects-images/threejs-profiol.png",
    project_blog:
      "Morden Profiol Wbsite With Javascript | React | Tailwind css | Responsive Website profiol desing.",
    Type: "React",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "ApexLegends.com Clone",
    video_key: "IqYbA6ZZ-e4",
    say_xi: "Have a great day!",
    say_xi_blog: "A clone of my favorite game website, Apex Legends — rebuilt from scratch.",
    technology_feature: [
      "html",
      "css",
      "Javascript",
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
    ],

    about_this_app:
      "Simple ApexLegnds Game Web application DropDown Feature Complex Responsive  and Contain Embed video",
    design_blog: "Desing From Apexlegends.com , I Recreate That Design",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Npm",
    package: [
      "@reduxjs/toolkit",
      "next",
      "react-icons",
      "react-redux",
      "swiper",
      "typescript",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/IqYbA6ZZ-e4",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/ApexLegends.com/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/projects-images/apex-legends.png",
    project_blog:
      "Simple ApexLegnds Game Web application DropDown Feature Complex Responsive",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Full-Stack Social Media App",
    video_key: "cLKsNVSyPMM",
    say_xi: "Hello, my friends!",
    say_xi_blog:
      "A full-stack social media project built with React, Tailwind CSS, and my first Node.js Express server.",
    technology_feature: [
      "html",
      "css",
      "Javascript",
      "Tailwind",
      "React",
      "Redux",
      "Node js",
      "Express js",
    ],
    about_this_app:
      "A Real Time Full Stack SocalMedia application User Can Upload Post With Image , User Can Make Post CRUD Operations & Reaction Feature , Comment CRUD & Contain User Profile CRUD and Friends Add , Remove RealTime Messanger Can send Image,Link,Text & RealTime With Pusher ",
    design_blog:
      "Basic Desing From Youtube and I Modified That Desing All Code By me an My Own Desing ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Npm",
    package: [
      "@mui/icons-material",
      "@reduxjs/toolkit",
      "formik",
      "javascript-time-ago",
      "jwt-decode",
      "material-ui-popup-state",
      "pusher-js",
      "react-dropzone",
      "react-easy-crop",
      "react-icons",
      "react-redux",
      "react-router-dom",
      "redux-persist",
      "swiper",
      "uuid",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/cLKsNVSyPMM",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/GrapeMedia/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/SocialMediaBackend-/archive/refs/heads/main.zip",
    project_image: "/projects-images/social-media.png",
    project_blog:
      "A Real Time Full Stack SocalMedia application User Can Upload Post With Image , User Can Make Post CRUD Operations & Reaction Feature , Comment CRUD & Contain User Profile CRUD and Friends Add , Remove RealTime Messanger Can send Image,Link,Text",
    Type: "React",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Shoe E-Commerce Server",
    video_key: "",
    say_xi: "",
    say_xi_blog: "",
    technology_feature: [
      "Node js",
      "Express js",
      "Postger sql",
      "Firebase",
      "JWT",
      "Stripe",
    ],
    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Backend/archive/refs/heads/main.zip",
    project_image: "/projects-images/server-project.png",
    project_blog:
      " User authentication Google auth , Facebook auth , Nike Auth ..more , Mind leven CRUD functionality",
    Type: "server",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Food Order & Admin Dashboard Server",
    video_key: "",
    say_xi: "",
    say_xi_blog: "",
    technology_feature: [
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
      "JWT",
    ],

    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link:
      "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
    project_image: "/projects-images/server-project.png",
    project_blog:
      "User authentication , Graphql  Mind leven CRUD functionality , Google auth , Facebook auth , Fastfood Auth,",
    Type: "server",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Deliveroo Server",
    video_key: "",
    say_xi: "",
    say_xi_blog: "",
    technology_feature: [
      "Node js",
      "Express js",
      "Firebase",
      "Postger sql",
      "JWT",
    ],

    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Deliveroo/archive/refs/heads/main.zip",
    project_image: "/projects-images/server-project.png",
    project_blog:
      "Node js Express With Postger Sql ,FireBase FireStore  CRUD functionality",
    Type: "server",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
];

/*
  {
    title: "",
    video_key: "",
    say_xi: "",
    say_xi_blog: "",
    technology_feature: [],
    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link: "",
    project_image: "",
    project_blog: "",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "",
  },
*/
