export const Project: Project_data[] = [
  {
    title: "Modern Next.js 13 Portfolio",
    video_key: "HvkrAjHJ-38",
    description:
      "My portfolio project built with Next.js 13 — featuring a clean UI, basic animations, and authentication. Contains star mode, Google/Facebook/GitHub/Instagram authentication, custom star color, basic Framer Motion animations, and embedded YouTube video.",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Framer Motion",
    ],
    about_this_app:
      "Contain StarMode , Drop Down NavBar , Authentication Google , Facebook , Github , Instgram , Custom Star Colour Basic Animation With Fraimer Motion , Conatin Embed Youtube Video ",
    design_blog: " Ui/Ux Desing & All Code Written by Me  ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use NPM",
    package: [
      "@heroicons/react",
      "@react-three/drei",
      "@react-three/fiber",
      "@reduxjs/toolkit",
      "framer-motion",
      "maath",
      "react-redux",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/v3LJMcWbcDQ",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/HyatMyat_Profiol/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/projects-images/nextjs-profiol.png",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Shoe E-Commerce & Admin Dashboard",
    video_key: "v3LJMcWbcDQ",
    description:
      "A full-stack responsive shoe e-commerce and admin dashboard. I gained extensive experience with complex UI, authentication, and CRUD operations. User can order with real-world Stripe payment. Admin can manage products, promotions, users, and view charts.",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Postger sql",
      "Firebase",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack Responsive Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Promote Product CRUD Admin Can look How Much User & Chart Pie , Chart line and Auth Google , Nike Auth",
    design_blog:
      "I Found Very Basic Ui Desing From Youtube , Then i get ideal To Make This All Desing By me 💚💚 ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use NPM",
    package: [
      "@mui/material",
      "@nivo/core",
      "@nivo/line",
      "@nivo/pie",
      "@reduxjs/toolkit",
      "@splidejs/react-splide",
      "@stripe/stripe-js",
      "@uiball/loaders",
      "next-auth",
      "next-themes",
      "firebase",
      "javascript-time-ago",
      "jwt-decode",
      "react-circular-progressbar",
      "react-datepicker",
      "react-easy-crop",
      "react-icons",
      "react-hot-toast",
      "react-redux",
      "react-tilt",
      "uuid",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/v3LJMcWbcDQ",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Shoes/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Backend/archive/refs/heads/main.zip",
    project_image: "/projects-images/shoe-ecommerce.png",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Admin Dashboard Web App",
    video_key: "yF1oJ7wzvWY",
    description:
      "Food ordering project with a GraphQL server, user authentication, CRUD operations, and social login integration. A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Responsive Desing",
    design_blog:
      "desing and all of ui create by my own ideal , conatin Backend ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Yarn",
    package: [
      "@apollo/client",
      "@emotion/react",
      "@emotion/styled",
      "@mui/material",
      "@mui/x-data-grid",
      "@nivo/bar",
      "@nivo/core",
      "@nivo/line",
      "@nivo/pie",
      "@reduxjs/toolkit",
      "@stripe/stripe-js",
      "@uiball/loaders",
      "encoding",
      "firebase",
      "graphql",
      "jwt-decode",
      "react-datepicker",
      "next-themes",
      "next-auth",
      "swiper",
      "uuid",
      "redux",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/yF1oJ7wzvWY",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/AdminDashboard/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
    project_image: "/projects-images/admin-dashboard-food.png",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Deliveroo Mobile App",
    video_key: "AxQ_Eli8gtk",
    description:
      "A React Native project built with Expo CLI, featuring Google authentication, REST API integration, and Google Maps functionality. It My First ReactNative App So The have a lot of Bug!, Feature Conatin Google Auth UserCanOrder Remove Order And Containe ReactNativeMap Justlike Deliveroo",
    technology_feature: [
      "Tailwind",
      "React Native",
      "Redux",
      "Type Script",
      "Expo",
      "Node js",
      "Express js",
      "Postger sql",
    ],

    about_this_app:
      "It My First ReactNative App So The have a lot of Bug!, Feature Conatin Google Auth UserCanOrder Remove Order And Containe ReactNativeMap Justlike Deliveroo",
    design_blog: "Desing From PapaReact YouTube Channel",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case we use Yarn and since this project was developed using expo we can also use the expo-cli to install the dependencies.",
    package: [
      "expo",
      "react-native-gesture-handler",
      "react-native-heroicons",
      "react-native-maps",
      "react-native-progress",
      "react-native-safe-area-context",
      "react-native-screens",
      "react-native-svg",
      "react-redux",
      "typescript",
      "nativewind",
      "expo-splash-screen",
      "@react-navigation/native",
      "@react-native-masked-view/masked-view",
      "@react-native-async-storage/async-storage",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/AxQ_Eli8gtk",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Deliveroo_Mobile.apk/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Deliveroo/archive/refs/heads/main.zip",
    project_image: "",
    Type: "React Native",
    project_Img_Mobile: [
      "/projects-images/deliveroo-1.jpg",
      "/projects-images/deliveroo-2.jpg",
      "/projects-images/deliveroo-3.jpg",
      "/projects-images/deliveroo-4.jpg",
      "/projects-images/deliveroo-5.jpg",
    ],
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Full-Stack Food Ordering Website",
    video_key: "yF1oJ7wzvWY",
    description:
      "Food ordering project with a GraphQL server, user authentication, CRUD operations, and social login integration. A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Responsive Desing",
    design_blog:
      "desing and all of ui create by my own ideal , conatin Backend ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Yarn",
    package: [
      "@apollo/client",
      "@emotion/react",
      "@emotion/styled",
      "@mui/material",
      "@mui/x-data-grid",
      "@nivo/bar",
      "@nivo/core",
      "@nivo/line",
      "@nivo/pie",
      "@reduxjs/toolkit",
      "@stripe/stripe-js",
      "@uiball/loaders",
      "encoding",
      "firebase",
      "graphql",
      "jwt-decode",
      "react-datepicker",
      "next-themes",
      "next-auth",
      "swiper",
      "uuid",
      "redux",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/yF1oJ7wzvWY",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/AdminDashboard/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
    project_image: "/projects-images/food-order.png",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "3 years ago",
  },

  {
    title: "Full-Stack AI ChatGPT Clone",
    video_key: "R90bxY4UwPg",
    description:
      "My first AI project — data comes from the OpenAI API. Ask questions just like in the real ChatGPT. A Real Time You Can Ask any thing & you can create new chat delete chat & Clear conversations Feature and google , microsoft Auth",
    technology_feature: [
      "html",
      "css",
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Firebase",
    ],

    about_this_app:
      "This Appp Contain Chate Create , Read , Update , Delete and Google Authentication , Microsoft Authentication , JWT Authentication functionality ",
    design_blog: "Desing From Realworld ChatGPT",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Npm ",
    package: [
      "@reduxjs/toolkit",
      "@uiball/loaders",
      "firebase",
      "firebase-admin",
      "nextjs-progressbar",
      "openai",
      "react-firebase-hooks",
      "react-icons",
      "react-redux",
      "react-simple-typewriter",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/R90bxY4UwPg",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Chat_GPT4/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/projects-images/chatgpt-clone.png",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Nike Admin Dashboard Web App",
    video_key: "v3LJMcWbcDQ",
    description:
      "A full-stack responsive shoe e-commerce and admin dashboard. I gained extensive experience with complex UI, authentication, and CRUD operations. A Real Time Full Stack Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Postger sql",
      "Firebase",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack Responsive Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Promote Product CRUD Admin Can look How Much User & Chart Pie , Chart line and Auth Google , Nike Auth",
    design_blog:
      "I Found Very Basic Ui Desing From Youtube , Then i get ideal To Make This All Desing By me 💚💚 ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use NPM",
    package: [
      "@mui/material",
      "@nivo/core",
      "@nivo/line",
      "@nivo/pie",
      "@reduxjs/toolkit",
      "@splidejs/react-splide",
      "@stripe/stripe-js",
      "@uiball/loaders",
      "next-auth",
      "next-themes",
      "firebase",
      "javascript-time-ago",
      "jwt-decode",
      "react-circular-progressbar",
      "react-datepicker",
      "react-easy-crop",
      "react-icons",
      "react-hot-toast",
      "react-redux",
      "react-tilt",
      "uuid",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/v3LJMcWbcDQ",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Shoes/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Backend/archive/refs/heads/main.zip",
    project_image: "/projects-images/nike-dashboard.png",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Modern Three.js Portfolio",
    video_key: "6wzf2ho-kzI",
    description:
      "A responsive 3.js portfolio website with star mode, background music, light/dark mode, embedded YouTube videos, and a mobile-responsive layout built with Vite. Morden Profiol Wbsite With Javascript | React | Tailwind css | Responsive Website profiol desing.",
    technology_feature: [
      "html",
      "css",
      "Javascript",
      "Tailwind",
      "React",
      "Redux",
      "Threes js",
      "Framer Motion",
    ],
    about_this_app:
      "This Responsive  Website is Make for showcase Project Profile ",
    design_blog:
      "very basic desing from My Friends , and I ReModified It All Code & Desing by Me ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I use npm beacuse We use older npm package .",
    package: [
      " maath",
      " @react-three/fiber",
      " @emailjs/browser",
      " framer-motion",
      " @react-three/fiber ",
      " @reduxjs/toolkit ",
      " react-router-dom",
      " react-tilt",
      " react-simple-typewriter",
      " react-icons",
      " react-spinkit",
      " react-vertical-timeline-component",
      " three",
    ],
    conclusion_blog:
      "As I said at the beginning, this is a great project for begginers and even for those who are not new to React . I bealive this is a grat project to have in a resume or portfolio. I am very happy with the app and I hope you will enjoy it as well.",
    youtube_link: "https://youtu.be/6wzf2ho-kzI",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/Profiol_2/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/projects-images/threejs-profiol.png",
    Type: "React",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "ApexLegends.com Clone",
    video_key: "IqYbA6ZZ-e4",
    description:
      "A clone of my favorite game website, Apex Legends — rebuilt from scratch. Simple ApexLegnds Game Web application DropDown Feature Complex Responsive",
    technology_feature: [
      "html",
      "css",
      "Javascript",
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
    ],

    about_this_app:
      "Simple ApexLegnds Game Web application DropDown Feature Complex Responsive  and Contain Embed video",
    design_blog: "Desing From Apexlegends.com , I Recreate That Design",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Npm",
    package: [
      "@reduxjs/toolkit",
      "next",
      "react-icons",
      "react-redux",
      "swiper",
      "typescript",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/IqYbA6ZZ-e4",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/ApexLegends.com/archive/refs/heads/main.zip",
    backend_dowload_link: "",
    project_image: "/projects-images/apex-legends.png",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Full-Stack Social Media App",
    video_key: "cLKsNVSyPMM",
    description:
      "A full-stack social media project built with React, Tailwind CSS, and my first Node.js Express server. A Real Time Full Stack SocalMedia application User Can Upload Post With Image , User Can Make Post CRUD Operations & Reaction Feature , Comment CRUD & Contain User Profile CRUD and Friends Add , Remove RealTime Messanger Can send Image,Link,Text",
    technology_feature: [
      "html",
      "css",
      "Javascript",
      "Tailwind",
      "React",
      "Redux",
      "Node js",
      "Express js",
    ],
    about_this_app:
      "A Real Time Full Stack SocalMedia application User Can Upload Post With Image , User Can Make Post CRUD Operations & Reaction Feature , Comment CRUD & Contain User Profile CRUD and Friends Add , Remove RealTime Messanger Can send Image,Link,Text & RealTime With Pusher ",
    design_blog:
      "Basic Desing From Youtube and I Modified That Desing All Code By me an My Own Desing ",
    dependencies_blog:
      "You can use Yarn or NPM to install the dependencies. In this case I am use Npm",
    package: [
      "@mui/icons-material",
      "@reduxjs/toolkit",
      "formik",
      "javascript-time-ago",
      "jwt-decode",
      "material-ui-popup-state",
      "pusher-js",
      "react-dropzone",
      "react-easy-crop",
      "react-icons",
      "react-redux",
      "react-router-dom",
      "redux-persist",
      "swiper",
      "uuid",
    ],
    conclusion_blog: "",
    youtube_link: "https://youtu.be/cLKsNVSyPMM",
    githhub_link: "https://github.com/HyatMyat4",
    frontend_dowload_link:
      "https://github.com/HyatMyat4/GrapeMedia/archive/refs/heads/main.zip",
    backend_dowload_link:
      "https://github.com/HyatMyat4/SocialMediaBackend-/archive/refs/heads/main.zip",
    project_image: "/projects-images/social-media.png",
    Type: "React",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Shoe E-Commerce Server",
    video_key: "",
    description:
      "User authentication Google auth , Facebook auth , Nike Auth ..more , Mind leven CRUD functionality",
    technology_feature: [
      "Node js",
      "Express js",
      "Postger sql",
      "Firebase",
      "JWT",
      "Stripe",
    ],
    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Nike_Backend/archive/refs/heads/main.zip",
    project_image: "/projects-images/server-project.png",
    Type: "server",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Food Order & Admin Dashboard Server",
    video_key: "",
    description:
      "User authentication , Graphql  Mind leven CRUD functionality , Google auth , Facebook auth , Fastfood Auth,",
    technology_feature: [
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
      "JWT",
    ],

    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link:
      "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
    project_image: "/projects-images/server-project.png",
    Type: "server",
    indevelopment: false,
    dateAgo: "3 years ago",
  },
  {
    title: "Deliveroo Server",
    video_key: "",
    description:
      "Node js Express With Postger Sql ,FireBase FireStore  CRUD functionality",
    technology_feature: [
      "Node js",
      "Express js",
      "Firebase",
      "Postger sql",
      "JWT",
    ],

    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link:
      "https://github.com/HyatMyat4/Deliveroo/archive/refs/heads/main.zip",
    project_image: "/projects-images/server-project.png",
    Type: "server",
    indevelopment: false,
    dateAgo: "3 years ago",
  },

  // ── REAL WORLD PROJECTS ──────────────────────────────────────────────────
  {
    title: "innorder — Restaurant Management SaaS",
    video_key: "",
    description:
      "Full-stack multi-tenant restaurant and hospitality management SaaS. Real-time order management, role-based access control, AI-powered features (OpenAI), analytics dashboards, multi-language support, and payment integration. Serving live customers across multiple restaurant branches.",
    technology_feature: [
      "Next js 13",
      "Type Script",
      "NestJS",
      "Postger sql",
      "Prisma",
      "Redis",
      "Socket.io",
      "Docker",
      "OpenAI",
      "Stripe",
    ],
    about_this_app:
      "Multi-tenant hospitality SaaS with real-time order management, AI features, analytics, and a React Native staff mobile app. Deployed on DigitalOcean with Docker and GitHub Actions CI/CD.",
    design_blog: "UI/UX designed and built from scratch",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link: "",
    project_image: "/projects-images/innorder-backoffice.png",
    project_imgs: [
      "/projects-images/innorder-backoffice.png",
      "/projects-images/innorder-guest-view.png",
      "/projects-images/innorder-staff-board.png",
    ],
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "2022 – Present",
    category: "realworld",
    live_url: "https://app.innorder.com/",
  },
  {
    title: "innorder — Product Landing Page",
    video_key: "",
    description:
      "Marketing and product landing page for the innorder hospitality SaaS platform. Built with Next.js and deployed on Cloudflare with multi-language support and a modern responsive design.",
    technology_feature: [
      "Next js 13",
      "Type Script",
      "Tailwind",
      "Cloudflare",
    ],
    about_this_app:
      "Public-facing product landing page for innorder, showcasing features, pricing, and demo booking. Deployed on Cloudflare Pages.",
    design_blog: "UI/UX designed and built from scratch",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link: "",
    project_image: "/projects-images/innorder-landing.png",
    project_imgs: [
      "/projects-images/innorder-landing.png",
      "/projects-images/innorder-landing-trusted.png",
      "/projects-images/innorder-landing-dining.png",
    ],
    preview_video: "/projects-images/innorder-landing-preview.mov",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "2022 – Present",
    category: "realworld",
    live_url: "https://innorder.com/en/",
  },
  {
    title: "Booking Platform — Online Reservation System",
    video_key: "",
    description:
      "Online table and service reservation platform with Omise payment gateway, LINE Bot messaging notifications, QR code check-in, BullMQ background job queues, and WebSocket real-time availability updates.",
    technology_feature: [
      "Next js 13",
      "Type Script",
      "Postger sql",
      "Prisma",
      "Omise",
      "Socket.io",
      "BullMQ",
      "Redis",
    ],
    about_this_app:
      "Full-stack booking platform with payment processing (Omise), real-time seat availability via WebSockets, LINE Bot push notifications, QR code check-in, and BullMQ job scheduling.",
    design_blog: "UI/UX designed and built from scratch",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link: "",
    project_image: "/projects-images/booking-home.png",
    project_imgs: [
      "/projects-images/booking-home.png",
      "/projects-images/booking-staff-dashboard.png",
      "/projects-images/booking-list.png",
      "/projects-images/booking-resource-management.png",
      "/projects-images/booking-pass-pricing.png",
    ],
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "2022 – Present",
    category: "realworld",
    live_url: "https://booking.innorder.com/",
  },
  {
    title: "Emojimeter — Customer Feedback SaaS",
    video_key: "",
    description:
      "Multi-tenant SaaS feedback and survey platform with Polar subscription billing, Cloudflare R2 file storage, Google Cloud Translate multi-language support, Sentry error monitoring, and white-label customisation.",
    technology_feature: [
      "Next js 13",
      "Type Script",
      "Postger sql",
      "Prisma",
      "Polar",
      "Cloudflare",
      "Sentry",
    ],
    about_this_app:
      "SaaS feedback platform with subscription billing (Polar), multi-language surveys, real-time analytics, and white-label support. Deployed with Cloudflare R2 and Sentry monitoring.",
    design_blog: "UI/UX designed and built from scratch",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link: "",
    project_image: "/projects-images/emojimeter-landing.png",
    project_imgs: [
      "/projects-images/emojimeter-landing.png",
      "/projects-images/emojimeter-survey-widget.png",
      "/projects-images/emojimeter-dashboard.png",
      "/projects-images/emojimeter-reports.png",
      "/projects-images/emojimeter-features.png",
      "/projects-images/emojimeter-pricing.png",
      "/projects-images/emojimeter-login.png",
    ],
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "2022 – Present",
    category: "realworld",
    live_url: "https://app.emojimeter.com/",
  },
  {
    title: "Crayon Post — School Communication Platform",
    video_key: "",
    description:
      "Turborepo monorepo school communication platform with a Next.js web dashboard and native iOS & Android mobile apps. Enables teachers, students, and parents to share announcements, media, and messages with Google Cloud Translate multi-language support.",
    technology_feature: [
      "Next js 13",
      "Type Script",
      "Turborepo",
      "Postger sql",
      "Prisma",
      "Cloudflare",
    ],
    about_this_app:
      "Monorepo school communication platform (web + mobile). Next.js dashboard for teachers and admins, React Native app for parents and students. Cloudflare R2 storage and Google Cloud Translate.",
    design_blog: "UI/UX designed and built from scratch",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link: "",
    project_image: "/projects-images/crayonpost-dashboard.png",
    project_imgs: [
      "/projects-images/crayonpost-dashboard.png",
    ],
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "2022 – Present",
    category: "realworld",
    live_url: "https://app.crayonpost.com/",
    live_url_2: "https://hampton.crayonpost.com/",
  },
  {
    title: "innorder Staff App",
    video_key: "",
    description:
      "Cross-platform React Native staff management app for the innorder platform. Real-time order notifications, in-app chat via Socket.io, push notifications with high-priority channels, offline SQLite storage, multi-language UI, and dark/light theme. Published to Apple App Store and Google Play Store. Bundle: com.innorder.staffapp (v2.1.2).",
    technology_feature: [
      "React Native",
      "Expo",
      "Type Script",
      "Redux",
      "Socket.io",
      "EAS",
    ],
    about_this_app:
      "Staff app for innorder: real-time orders, in-app chat, push notifications, offline storage, OTA updates (Expo Updates). Published to App Store and Play Store via EAS Build.",
    design_blog: "UI/UX designed and built from scratch",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link: "",
    project_image: "",
    Type: "React Native",
    project_Img_Mobile: [
      "/projects-images/innorder-staff-appstore.png",
      "/projects-images/innorder-staff-playstore.png",
    ],
    indevelopment: false,
    dateAgo: "2022 – Present",
    category: "realworld",
    live_url: "",
    playstore_url: "https://play.google.com/store/apps/details?id=com.innorder.innorderstaffapp",
    appstore_url: "https://apps.apple.com/us/app/innorder-staff-app/id8744053575",
  },
  {
    title: "Crayon Post Mobile App",
    video_key: "",
    description:
      "React Native mobile companion to the Crayon Post school platform. Provides teachers and parents with announcements, messaging, and media sharing. Published to both App Store and Google Play Store with OTA update delivery (Expo Updates). Bundle: com.crayonpost.app.",
    technology_feature: [
      "React Native",
      "Expo",
      "Type Script",
      "EAS",
      "Cloudflare",
    ],
    about_this_app:
      "Mobile app for Crayon Post school platform. Push notifications, media sharing, multi-language support. Deployed to App Store and Play Store via EAS Build with OTA updates.",
    design_blog: "UI/UX designed and built from scratch",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link: "",
    project_image: "",
    Type: "React Native",
    project_Img_Mobile: [
      "/projects-images/crayonpost-appstore.png",
      "/projects-images/crayonpost-playstore.png",
    ],
    indevelopment: false,
    dateAgo: "2022 – Present",
    category: "realworld",
    live_url: "",
    playstore_url: "https://play.google.com/store/apps/details?id=com.crayonpost.app",
    appstore_url: "https://apps.apple.com/us/app/crayon-post/id6760888842",
  },
  {
    title: "Maple Bear Thailand — School App",
    video_key: "",
    description:
      "Mobile app for Maple Bear Thailand, a Canadian bilingual education franchise. Enables school-to-parent communication, announcements, chat, and student activity updates. Published to the Apple App Store and Google Play Store with OTA update support. Bundle: com.maplebear.mobile.",
    technology_feature: [
      "React Native",
      "Expo",
      "Type Script",
      "EAS",
    ],
    about_this_app:
      "School communication app for Maple Bear Thailand franchise. Push notifications, announcements, parent-teacher chat, and activity feeds. Deployed to App Store and Play Store via EAS Build with OTA updates.",
    design_blog: "UI/UX designed and built from scratch",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link: "",
    project_image: "",
    Type: "React Native",
    project_Img_Mobile: [
      "/projects-images/maplebear-appstore.png",
      "/projects-images/maplebear-playstore.png",
    ],
    indevelopment: false,
    dateAgo: "2022 – Present",
    category: "realworld",
    live_url: "",
    playstore_url: "https://play.google.com/store/apps/details?id=com.maplebear.mobile",
    appstore_url: "https://apps.apple.com/us/app/maple-bear-thailand/id6756017469",
  },
];

/*
  {
    title: "",
    video_key: "",
    description: "",
    technology_feature: [],
    about_this_app: "",
    design_blog: "",
    dependencies_blog: "",
    package: [],
    conclusion_blog: "",
    youtube_link: "",
    githhub_link: "",
    frontend_dowload_link: "",
    backend_dowload_link: "",
    project_image: "",
    Type: "Next js 13",
    indevelopment: false,
    dateAgo: "",
  },
*/
